backend:
  name: git-gateway
  repo: zanonnicola/inextenso-js
  branch: master

media_folder: static/img
public_folder: /assets

collections:
  - label: 'Articles'
    name: 'article'
    folder: 'src/pages/articles'
    create: true
    fields:
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'article' }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub Title", name: "subtitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
